# Generated by Django 5.2 on 2025-05-16 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0001_initial'),
        ('Materiels', '0002_alter_materiel_etat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenanceprediction',
            options={'ordering': ['-prediction_date']},
        ),
        migrations.AlterField(
            model_name='maintenanceprediction',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='Materiels.materiel'),
        ),
    ]
