# Generated by Django 5.2 on 2025-04-28 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Analytics', '0001_initial'),
        ('Materiels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceprediction',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Materiels.materiel'),
        ),
        migrations.AddField(
            model_name='maintenanceprediction',
            name='model_used',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Analytics.predictionmodel'),
        ),
    ]
