# Generated by Django 5.2 on 2025-04-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='type_ticket',
            field=models.CharField(choices=[('incident', 'Incident'), ('demande', 'Demande'), ('maintenance', 'Maintenance Préventive')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('reseau', 'Problème Réseau'), ('materiel', 'Problème Matériel'), ('logiciel', 'Problème Logiciel'), ('securite', 'Problème de Sécurité'), ('compte', 'Problème de Compte'), ('autre', 'Autre')], max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours'), ('fermé', 'Fermé')], max_length=50),
        ),
    ]
