# Generated by Django 5.2 on 2025-05-12 12:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0003_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='TicketComment',
        ),
        migrations.AlterModelOptions(
            name='ticketcomment',
            options={'ordering': ['-created_at']},
        ),
    ]
