# Generated by Django 5.2 on 2025-04-28 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_achat', models.DateField()),
                ('etat', models.CharField(choices=[('en_panne', 'En_panne'), ('en_marche', 'En_marche')], default='en_marche', max_length=50)),
                ('marque', models.CharField(max_length=100)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ecrant',
            fields=[
                ('materiel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Materiels.materiel')),
                ('taille', models.CharField(max_length=50)),
            ],
            bases=('Materiels.materiel',),
        ),
        migrations.CreateModel(
            name='Impriment',
            fields=[
                ('materiel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Materiels.materiel')),
                ('type', models.CharField(max_length=50)),
            ],
            bases=('Materiels.materiel',),
        ),
        migrations.CreateModel(
            name='Ordinateur',
            fields=[
                ('materiel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Materiels.materiel')),
                ('system_exp', models.CharField(max_length=100)),
                ('rom', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
            ],
            bases=('Materiels.materiel',),
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('materiel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Materiels.materiel')),
                ('numero', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('portable', 'Portable'), ('bureau', 'Bureau')], max_length=50)),
            ],
            bases=('Materiels.materiel',),
        ),
    ]
