# Generated by Django 5.2 on 2025-05-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Materiels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='etat',
            field=models.CharField(choices=[('en_panne', 'En_panne'), ('en_marche', 'En_marche'), ('en_réparation', 'En_réparation')], default='en_marche', max_length=50),
        ),
    ]
