# Generated by Django 5.2 on 2025-06-04 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Materiels', '0002_alter_materiel_etat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat_initial', models.CharField(max_length=50)),
                ('evenement', models.CharField(max_length=255)),
                ('etat_suivant', models.CharField(max_length=50)),
                ('date_transition', models.DateTimeField(auto_now_add=True)),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Materiels.materiel')),
            ],
        ),
    ]
