# Generated by Django 5.2 on 2025-06-07 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Materiels', '0003_transition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logiciel',
            fields=[
                ('materiel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Materiels.materiel')),
                ('version', models.CharField(max_length=50)),
                ('cle_licence', models.CharField(max_length=100)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('systeme_compatible', models.CharField(max_length=100)),
            ],
            bases=('Materiels.materiel',),
        ),
        migrations.CreateModel(
            name='Peripherique',
            fields=[
                ('materiel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Materiels.materiel')),
                ('type_peripherique', models.CharField(choices=[('clavier', 'Clavier'), ('souris', 'Souris'), ('casque', 'Casque'), ('webcam', 'Webcam'), ('microphone', 'Microphone'), ('haut_parleur', 'Haut-parleur'), ('autre', 'Autre')], max_length=50)),
                ('connectivite', models.CharField(blank=True, max_length=100, null=True)),
                ('compatible_os', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('Materiels.materiel',),
        ),
        migrations.CreateModel(
            name='Routeur',
            fields=[
                ('materiel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Materiels.materiel')),
                ('ip_adresse', models.GenericIPAddressField(blank=True, null=True)),
                ('nb_ports', models.IntegerField()),
                ('vitesse', models.CharField(max_length=50)),
            ],
            bases=('Materiels.materiel',),
        ),
        migrations.CreateModel(
            name='Serveur',
            fields=[
                ('materiel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Materiels.materiel')),
                ('processeur', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=50)),
                ('stockage', models.CharField(max_length=100)),
                ('systeme_exploitation', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('ip_adresse', models.GenericIPAddressField(blank=True, null=True)),
            ],
            bases=('Materiels.materiel',),
        ),
        migrations.CreateModel(
            name='StockageExterne',
            fields=[
                ('materiel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Materiels.materiel')),
                ('type_stockage', models.CharField(max_length=50)),
                ('capacite', models.CharField(max_length=50)),
            ],
            bases=('Materiels.materiel',),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='etat',
            field=models.CharField(choices=[('en_panne', 'En_panne'), ('en_marche', 'En_marche'), ('en_réparation', 'En_réparation'), ('en_stock', 'En stock')], default='en_marche', max_length=50),
        ),
        migrations.DeleteModel(
            name='Transition',
        ),
    ]
