# Generated by Django 5.2 on 2025-06-07 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Materiels', '0004_logiciel_peripherique_routeur_serveur_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impriment',
            old_name='type',
            new_name='impriment_type',
        ),
        migrations.RenameField(
            model_name='telephone',
            old_name='type',
            new_name='telephone_type',
        ),
    ]
