# Generated by Django 5.2 on 2025-05-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('technicien', 'Technicien'), ('chefDepartement', 'Chef_Departement'), ('utilisateurNormal', 'UtilisateurNormal')], max_length=20),
        ),
    ]
