# Generated by Django 5.2 on 2025-05-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Users', '0002_alter_app_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app_user',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='app_user',
            name='prenom',
        ),
        migrations.AlterField(
            model_name='app_user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('technicien', 'Technicien'), ('utilisateurNormal', 'UtilisateurNormal')], max_length=20),
        ),
    ]
