# Generated by Django 5.2 on 2025-05-05 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Users', '0003_remove_app_user_nom_remove_app_user_prenom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app_user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='department',
            name='service',
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='App_Users.department')),
            ],
        ),
        migrations.AddField(
            model_name='app_user',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_Users.service'),
        ),
    ]
