# Generated by Django 5.2 on 2025-05-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Users', '0004_remove_app_user_department_remove_department_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_user',
            name='avatar',
            field=models.ImageField(default='default_avatar.png', upload_to='avatars/'),
        ),
    ]
