# Generated by Django 5.2 on 2025-05-15 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Users', '0005_app_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app_user',
            name='avatar',
        ),
    ]
