name: Tests fullstack (React + Django)

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_DATABASE: parc_informatique
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        working-directory: Project_APP/backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Appliquer les migrations Django
        working-directory: Project_APP/backend
        run: python manage.py migrate

      - name: Lancer les tests Django
        working-directory: Project_APP/backend
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: 3306
          MYSQL_DATABASE: parc_informatique
          MYSQL_USER: root
          MYSQL_PASSWORD: ""
        run: pytest

  frontend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        working-directory: Project_APP/frontend
        run: npm install

      - name: Lancer les tests React
        working-directory: Project_APP/frontend
        run: npm run test
