name: Tests fullstack (React + Django)

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:

  backend-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: ""  # mot de passe vide
          MYSQL_DATABASE: parc_informatique
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Project_APP/backend/requirements.txt

      - name: Apply migrations
        run: python manage.py migrate

      - name: Run backend tests
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: 3306
          MYSQL_DATABASE: parc_informatique
          MYSQL_USER: root
          MYSQL_PASSWORD: ""
        run: pytest


  frontend-test:
    runs-on: ubuntu-latest

    needs: backend-test   # attendre que backend-test soit fini

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        working-directory: ./frontend   # adapte selon le chemin de ton React
        run: npm install

      - name: Run frontend tests
        working-directory: ./frontend
        run: npm test -- --watchAll=false
